// Movie.kt - Entity representing a movie in the local Room database
package com.example.movieexplorer

import androidx.room.Entity
import androidx.room.PrimaryKey

// Room entity for the 'movies' table
@Entity(tableName = "movies")
data class Movie(
    // Primary key, auto-generated by Room
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    // Movie title (required)
    val title: String,
    // Optional fields for movie details
    val year: String?,
    val rated: String?,
    val released: String?,
    val runtime: String?,
    val genre: String?,
    val director: String?,
    val writer: String?,
    val actors: String?,
    val plot: String?
) 